config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: "sessions#omniauth"

  root 'welcome#index'

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update, :destroy]
  
  resources :gyms do
    member do
      get 'join'
      get 'leave'
    end
  end

  resources :workouts do
    resources :scores, shallow: true
  end

end

app/models/workout.rb
class Workout < ApplicationRecord
    has_many :scores
    has_many :users, through: :scores
    validates :name, presence: true, uniqueness: true
    validates :category, :description, presence: true

    scope :category_nav_selector, -> (category) {where('category = ?', category)}
    scope :wod_group_selector, -> (wod_group) {where('wod_group = ?', wod_group)}
    
    def self.search(search)
        where("LOWER(name) LIKE :term OR LOWER(wod_group) LIKE :term OR LOWER(category) LIKE :term OR LOWER(description) LIKE :term", term: "%#{search}%")
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
    before_action :find_workout, only: [:show, :edit, :update, :destroy]
    before_action :redirect_if_not_logged_in?, only: [:edit, :update, :destroy]

    def index
        if params[:category]
            @workouts = Workout.category_nav_selector(params[:category])
        else
            @workouts = Workout.all
        end
        if params[:workout] && !params[:workout][:wod_group].blank?
            @workouts = Workout.wod_group_selector(params[:workout][:wod_group])
        end
    end

    def show
    end

    def new
        @workout = Workout.new
    end

    def create
        @workout = Workout.new(workout_params)
        if @workout.save
            redirect_to workout_path(@workout)
        else
            render :new
        end
    end

    def edit
        if !@workout.scores.blank?
            redirect_to workouts_path
        end
    end

    def update
        if @workout.update(workout_params)
            redirect_to workout_path(@workout)
        else
            render :edit
        end
    end

    def destroy
        @workout.destroy
        redirect_to workouts_path
    end

    private
    def workout_params
        params.require(:workout).permit(:name, :wod_group, :category, :description, :about)
    end

    def find_workout
        @workout = Workout.find(params[:id]) rescue not_found
    end
end

app/helpers/workouts_helper.rb
module WorkoutsHelper

    def helper_edit_workout_link
        if logged_in? && @workout.scores.blank?
            link_to "Edit", edit_workout_path(@workout), class: "edit-score-btn"
        end
    end

    def helper_delete_workout_link
        if logged_in? && @workout.scores.blank?
            button_to "Delete", workout_path(@workout), method: :delete, data: { confirm: "Are you sure?" }, class: "delete-score-btn"
        end
    end

end

app/views/workouts/_form.html.erb
<%= render partial: 'layouts/error', locals: { object: @workout } %>

    <%= f.label :name %>
    <%= f.text_field :name, {placeholder: "JT", class: "form-group" } %>

    <%= f.label :wod_group %>
        <%= f.text_field :wod_group, {list: "group_autocomplete", placeholder: "Select or Add new option", class: "form-group"} %>
            <datalist id="group_autocomplete">
                <% Workout.all.map(&:wod_group).uniq.each do |select| %>
                    <option value="<%= select %>">
                <% end %>
            </datalist>

    <%= f.label :category %>
    <%= f.select :category, options_for_select(Workout.all.map {|select| [ select.category ]}.uniq), {prompt: true}, class: "form-group" %>

    <%= f.label :description %>
    <%= f.text_area :description, {placeholder: "(line break by adding comma ',' in the end) 21-15-9 reps of: Handstand push-ups, Ring dips, Push-ups", class: "form-group"} %>

    <%= f.label :about %>
    <%= f.text_area :about, {placeholder: "JT is in honor of Navy Petty Officer First Class Jeff Taylor, 30, of Little Creek, VA, who was killed in Afghanistan.", class: "form-group"} %>

app/views/workouts/_workout.html.erb
<p><%= workout.wod_group %></p>
<p><%= workout.category %></p>
<% workout.description.split(/[\,\:]/).each do |value| %>
    <p><%= value %></p>
<% end %>

app/views/workouts/edit.html.erb
<div class="container">  
    <h2>Edit <%= @workout.name %></h2>
    <hr>

        <div class="col"> 
            <%= form_for @workout do |f| %>
                <%= render partial: 'form', locals: { f: f } %>
                <%= f.submit "Update Workout", {class: "gym-btn"} %>
            <% end %>
        </div>
</div>

app/views/workouts/index.html.erb
<div class="container">  
    <h2>Workouts</h2>

    Filter by Group:
        <%= form_tag(workouts_path, method: "get") do %>
            <%= collection_select :workout, :wod_group, Workout.select(:wod_group).distinct, :wod_group, :wod_group, prompt: true %>
            <%= submit_tag "Filter", class: "filter-btn" %>
        <% end %>
        <br>

        <%= link_to "Add a workout", new_workout_path, {class: "add-workout-btn"} %>
        
        <hr>
    
        <ul class="workouts">
            <% @workouts.each do | workout| %>
                <li>
                    <%= link_to workout_path(workout), {class: "workout-link"} do %>
                        <h3><%= workout.name %>
                        <%= render partial: 'workout', locals: { workout: workout } %>
                    <% end %>
                </li>
            <% end %>
        </ul>
</div>

app/views/workouts/new.html.erb
<div class="container">  
    <h2>Create a Workout</h2>
    <hr>

        <div class="col"> 
            <%= form_for @workout do |f| %>
                <%= render partial: 'form', locals: { f: f } %>
                <%= f.submit "Create Workout", {class: "gym-btn"} %>
            <% end %>
        </div>
</div>

app/views/workouts/show.html.erb
<div class="container">
    <h2><%= @workout.name %></h2>
    <hr>

        <ul class="workout-show">
            <li>
                <%= render @workout %>
                <br>
                <p><%= @workout.about %></p>
            </li>
        </ul>

        <br>
            <%= helper_edit_workout_link %>
            <%= helper_delete_workout_link %>
        <br><br><br>     
        
        <%= link_to "Check Scores", workout_scores_path(@workout), class: "score-btn" %>
</div>