config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: "sessions#omniauth"

  root 'welcome#index'

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update, :destroy]
  
  resources :gyms do
    member do
      get 'join'
      get 'leave'
    end
  end

  resources :workouts do
    resources :scores, shallow: true
  end

end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :gym, optional: true
    has_many :scores
    has_many :workouts, through: :scores
    
    validates :email, presence: true, uniqueness: true
    validates :first_name, :last_name, presence: true
    has_secure_password
    #accepts_nested_attributes_for :gym

    def gym_attributes=(hash_of_attributes)
        if !hash_of_attributes["name"].blank?
            self.gym = Gym.find_or_create_by(hash_of_attributes)
        end
    end

    def self.from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
          u.email = auth['info']['email']
          u.first_name = auth['info']['first_name']
          u.last_name = auth['info']['last_name']
          u.password = SecureRandom.hex(15)
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def new
        @user = User.new
        @user.gym = Gym.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            @user.build_gym
            render :new
        end
    end

    def show
    end

    def edit
        if @user != current_user
            redirect_to user_path(current_user)
        end
        @user.build_gym
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit
        end
    end

    def destroy
        @user.destroy
        redirect_to root_path
    end

    private
    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :age, :height, :weight, :country, :gym_id, gym_attributes: [:name, :website, :address])
    end

    def find_user
        @user = User.find(params[:id]) rescue not_found
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    def helper_display_or_hide_email
        @user.email unless @user != current_user
    end

    def helper_edit_profile_link
        link_to "Edit Profile", edit_user_path(@user), class:"edit-score-btn" unless @user != current_user
    end

    def helper_delete_profile_link
        link_to "Delete Profile", user_path(@user), method: 'delete', class:"delete-score-btn" unless @user != current_user
    end
    
end

app/views/users/_form.html.erb
<%= errors_message(@user) %>

    <div class="col">
        <%= f.label :email %><br>
        <%= f.email_field :email, {placeholder: "dave@crossfit.com (required)" , class: "form-group"} %><br>

        <%= f.label :password %><br>
        <%= f.password_field :password, {placeholder: "password (required)", class: "form-group"} %><br>

        <%= f.label :first_name %><br>
        <%= f.text_field :first_name, {placeholder: "Dave (required)", class: "form-group"} %><br>

        <%= f.label :last_name %><br>
        <%= f.text_field :last_name, {placeholder: "Castro (required)", class: "form-group"} %><br>

        <%= f.label :age %><br>
        <%= f.number_field :age, {placeholder: 32, class: "form-group"} %><br>
        
        <%= f.label :height, "Height (in)" %><br>
        <%= f.number_field :height, {in: 1.00..8.00, step: 0.01, placeholder: "5.11", class: "form-group"} %><br>

        <%= f.label :weight, "Weight (lbs)" %><br>
        <%= f.number_field :weight, {placeholder: 171, class: "form-group"} %><br>
        
        <%= f.label :country %><br>
        <%= f.text_field :country, {placeholder: "United States", class: "form-group"} %><br>
    </div>

    <div class="col">
        <h3>Select Your CrossFit Affiliate Gym:</h3>
            <%= f.collection_select :gym_id, Gym.all, :id, :name, {prompt: true} %>
        <p>If not found, add your gym below: </p>
            <%= f.fields_for :gym do |g| %>
                <%= render partial: 'gyms/form', locals: { f: g } %>             
            <% end %>
    <div>

app/views/users/_user.html.erb
<% if @user.country? %>
    <p>Country: <%= @user.country %></p>
<% end %>

<% if @user.age? %>
    <p>Age: <%= @user.age %></p>
<% end %>

<% if @user.height? %>
    <p>Height: <%= @user.height %></p>
<% end %>

<% if @user.weight? %>
    <p>Weight: <%= @user.weight %></p>
<% end %>
            
<% if @user.gym %>
    <h4>Gym Affiliate: <%= link_to @user.gym.name, gym_path(@user.gym), class:"profile-gym-link" %></h4>
<% end %>

app/views/users/edit.html.erb
<div class="container">
    <h2>Edit <%= @user.first_name %> <%= @user.last_name %> Profile</h2>
    <hr>
    
        <%= form_for @user do |f| %>
            <%= render partial: 'form', locals: { f: f } %>
        <%= f.submit "Update Account", {class: "user-account-btn"} %>
        <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
    <h2>Create Your Account</h2>
    <p>Keep track your results and compete with athletes all over the world. <%= link_to "Already have an account?", login_path %></p>
    <hr>
    
        <%= form_for(@user, url: signup_path) do |f| %>
            <%= render partial: 'form', locals: { f: f } %>
        <%= f.submit "Create Account", {class: "user-account-btn"} %>
        <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <h2><%= @user.first_name %> <%= @user.last_name %> Profile Page</h2>

    <ul class="profile">
        <li>
            <p><%= helper_display_or_hide_email %></p>
            <%= render 'user' %>
        </li>
    </ul>
            <%= helper_edit_profile_link %>
            <%= helper_delete_profile_link %>
            <br><br>
        <hr>

    <h3>Your Workout Scores</h3>

        <% @user.scores.each do |score| %>
            <% if score.public? || @user == current_user %>
                <ul class="workout-show">
                    <li>    
                        <h4><%= link_to score.workout.name, workout_scores_path(score.workout), class:"profile-gym-link" %></h4>
                            <%= render partial: 'scores/score', locals: { score: score } %>
                        <p><%= helper_public_private(score) %></p>
                    </li>
            <% end %>
                        <%= helper_edit_score_link(score) %>
                        <%= helper_delete_score_link(score) %>
                    <br>
                </ul>
        <% end %>
</div>