config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: "sessions#omniauth"

  root 'welcome#index'

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update, :destroy]
  
  resources :gyms do
    member do
      get 'join'
      get 'leave'
    end
  end

  resources :workouts do
    resources :scores, shallow: true
  end

end

app/models/gym.rb
class Gym < ApplicationRecord
    has_many :users, dependent: :destroy
    validates :name, presence: true, uniqueness: true

    #gym with most users
    scope :gym_most_users, -> {joins(:users).group(:gym_id).order('COUNT(users.id) desc').limit(1)}
end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
    include GymsHelper
    before_action :find_gym, only: [:join, :leave, :show, :edit, :update, :destroy]
    before_action :redirect_if_not_belong_to_gym, only: [:edit, :update, :destroy]
    before_action :redirect_if_not_logged_in?, only: [:join, :leave, :new, :create]

    def index
        @gyms = Gym.all
    end

    def join
        current_user.update_attribute(:gym_id, @gym.id)
        redirect_to gym_path(@gym)
    end

    def leave
        current_user.update_attribute(:gym_id, nil)
        redirect_to gyms_path
    end

    def show
    end

    def new
        @gym = Gym.new
    end

    def create
        @gym = Gym.new(gym_params)
        if @gym.save
            redirect_to gym_path(@gym)
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @gym.update(gym_params)
            redirect_to gym_path(@gym)
        else
            render :edit
        end
    end

    def destroy
        @gym.destroy
        redirect_to gyms_path
    end

    private
    def gym_params
        params.require(:gym).permit(:name, :website, :address)
    end

    def find_gym
        @gym = Gym.find(params[:id]) rescue not_found
    end

    def redirect_if_not_belong_to_gym
        redirect_to gyms_path if !current_user_belongs_to_gym
    end

end

app/helpers/gyms_helper.rb
module GymsHelper
    
    def current_user_belongs_to_gym
        @gym.users.include?(current_user)
    end

    def helper_gym_users_link(user)
        link_to "#{user.first_name} #{user.last_name}", user_path(user), {class: "profile-gym-link"}
    end

    def helper_leave_join_gym_link
        if current_user_belongs_to_gym
            link_to "Leave", leave_gym_path(@gym), class: "leave-gym-btn"
        else
            link_to "Join", join_gym_path(@gym), class: "join-gym-btn"
        end
    end

    def helper_gym_website
        link_to "Website", "http://#{@gym.website}", {target: "_blank", class: "gym-ext-link"} unless @gym.website.blank?
    end

    def helper_gym_address
        "Address: #{@gym.address}" unless @gym.address.blank?
    end

end

app/views/gyms/_form.html.erb
<%= f.label :name %><br>
<%= f.text_field :name, {placeholder: "Crossfit", class: "form-group"} %><br>

<%= f.label :website %><br>
<%= f.text_field :website, {placeholder: "crossfit.com", class: "form-group"} %><br>

<%= f.label :address %><br>
<%= f.text_field :address, {placeholder: "2617 Broadway, Boulder, CO 80304, United States", class: "form-group"} %><br>

app/views/gyms/edit.html.erb
<div class="container">
    <h2>Edit <%= @gym.name %></h2>
    <hr>
        <%= render partial: 'layouts/error', locals: { object: @gym } %>

        <div class="col">
            <%= form_for @gym do |f| %>
                <%= render partial: 'form', locals: { f: f } %>
                <%= f.submit "Update Gym", {class: "gym-btn"} %>
            <% end %>
        </div>
</div>

app/views/gyms/index.html.erb
<div class="container">

    <h2>CrossFit Affiliate Gyms</h2>
    <br>
        <%= link_to "Add a gym", new_gym_path, {class: "add-gym-btn"} %>
    <hr>

    <ul class="gyms">
        <% @gyms.each do |gym| %>
            <li>
                <p><%= link_to gym.name, gym_path(gym), {class: "gyms-link"} %></p>
            </li>
        <% end %>
    </ul>
</div>

app/views/gyms/new.html.erb
<div class="container">
    <h2>Create Gym</h2>
    <hr>
        <%#= render partial: 'layouts/error', locals: { object: @gym } %>
        <%= errors_message(@gym) %>

        <div class="col">  
            <%= form_for @gym do |f| %>
                <%= render partial: 'form', locals: { f: f } %>
                <%= f.submit "Submit Gym", {class: "gym-btn"} %>
            <% end %>
        </div>
</div>

app/views/gyms/show.html.erb
<div class="container">
    
    <div class="gym-show">
        <h2><%= @gym.name %></h2>
        <p><%= helper_gym_website %></p>
        <p><%= helper_gym_address %></p>
    </div>
    <br>

        <% if current_user_belongs_to_gym %>
            <%= link_to "Edit Gym", edit_gym_path(@gym), class: "edit-gym-btn" %>
            <%= link_to "Delete Gym", gym_path(@gym), method: 'delete', data: { confirm: "Are you sure? All #{@gym.name}'s Athletes will also be deleted" }, class: "delete-gym-btn" %>
            <br><br>
        <% end %>
    <hr>

    <h3>Athletes:</h3>
        <%= helper_leave_join_gym_link %>
        <br><br>

        <% @gym.users.each do |user| %>
            <ul class="workout-show">
                <li>
                    <p><%= helper_gym_users_link(user) %></p>
                </li>
            </ul>
        <% end %>
</div>