config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/auth/:provider/callback', to: "sessions#omniauth"

  root 'welcome#index'

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"

  delete '/logout', to: "sessions#destroy"

  resources :users, only: [:show, :edit, :update, :destroy]
  
  resources :gyms do
    member do
      get 'join'
      get 'leave'
    end
  end

  resources :workouts do
    resources :scores, shallow: true
  end

end

app/views/layouts/_error.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
        <span class="req">
    
            <%= pluralize(object.errors.count, "error") %>:<br>

            <ul>
                <% object.errors.each do |error| %>
                    <ol><%= error.full_message %></ol>
                <% end %>
            </ul>
            <br>
        </span>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
    <div class="a"><%= link_to "HOME", root_path %></div>
        <div class="dropdown">
            <button class="dropbtn">WORKOUTS
              <i class="fa fa-caret-down"></i>
            </button>
                <div class="dropdown-content">
                    <div class="a"><%= link_to "FOR TIME", workouts_path(category: "For time") %></div>
                    <div class="a"><%= link_to "AMRAP", workouts_path(category: "AMRAP") %></div>
                    <div class="a"><%= link_to "EMOM", workouts_path(category: "EMOM") %></div>
                    <div class="a"><%= link_to "ALL", workouts_path %></div>
                </div>
        </div>
        <div class="a"><%= link_to "GYMS", gyms_path %></div>
        <% if logged_in? %>
            <div class="a"><%= link_to "PROFILE", user_path(current_user.id) %></div>
            <div class="a"><%= link_to "LOG OUT", logout_path, method: 'delete' %></div>
        <% else %>
            <div class="a"><%= link_to "SIGN UP", signup_path %></div>
            <div class="a"><%= link_to "LOG IN", login_path %></div>
        <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Crossfit Benchmark Project</title>
        <meta name="viewport" content="width=device-width,initial-scale=1">
          <%= csrf_meta_tags %>
          <%= csp_meta_tag %>
          <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
          <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>
    <body>

      <%= render 'layouts/navigation' %>

      <div id="main-container">
        <%= yield %>
      </div>
    
      <footer>
        <small>&copy; 2021 <strong>CrossFit Benchmark Corporation.</strong> All Rights Reserved.</small>
      </footer>
    </body> 
</html>